### ISSUE TITLE
Add xref-id's for "analoge dragers" and "golven"

### ISSUE THREAD

**Issue by maartends** [viaacode/skryv2crm#2]
Several ID's should be added to both these files:

https://github.com/viaacode/skryv2crm/blob/master/src/main/resources/production_xref_analoge_drager.json
https://github.com/viaacode/skryv2crm/blob/master/src/main/resources/production_xref_golf.json

These are:
- Analoge dragers
"DV-formaten" in skryv--> "430502": "DV-formaten" in Teamleader
"dvd" in skryv --> "430506": "dvd" in Teamleader
"cd" in skryv --> "430507": "cd" in Teamleader

- Golf
"Golf 7" --> "430449": "Golf 7" in Teamleader
"Golf 9" --> "430451": "Golf 9" in Teamleader

**Comment by maartends** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [skryv2crm: Nieuwe waarden Analoge dragers en Golf in SA in contract.viaa.be](https://trello.com/c/9cW1jZrv/650-skryv2crm-nieuwe-waarden-analoge-dragers-en-golf-in-sa-in-contractviaabe)

**Comment by RudolfDG** [comment]
This issue is fixed in: 4e1301d78f3ff10f0bf8c4d026f93c7ee30f548a.

**Comment by maartends** [comment]
Done.
